export interface URDFStudioModel {
  id: string;
  name: string;
  author: string;
  description: string;
  thumbnail: string;
  category: string;
  stars: number;
  downloads: number;
  tags: string[];
  lastUpdated: string;
  urdfPath?: string;
  urdfFile?: string;
  previewVideo?: string;
  // Optional Chinese translations
  name_zh?: string;
  description_zh?: string;
  tags_zh?: string[];
  author_zh?: string;
}

export const URDF_STUDIO_MODELS: URDFStudioModel[] = [
  {
    id: '1b74b8e3-8995-4d6d-b3a8-a73fb7983631',
    name: 'Unitree Go2',
    name_zh: 'Unitree Go2 四足机器人',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'High-performance quadruped robot for research and entertainment.',
    description_zh: '高性能四足机器人，适用于科研和娱乐场景。',
    thumbnail: '/library/urdf/unitree/go2_description/thumbnail.png',
    category: 'Quadruped',
    stars: 1250,
    downloads: 3200,
    tags: ['Research', 'Quadruped', 'Mobile'],
    tags_zh: ['科研', '四足', '移动'],
    lastUpdated: '2026-01-17',
    urdfPath: '/library/urdf/unitree/go2_description'
  },
  {
    id: 'f84a878f-aa6b-4086-920f-b58429a59e82',
    name: 'Unitree Go1',
    name_zh: 'Unitree Go1 四足机器人',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'Consumer-grade quadruped robot for education and beginner research.',
    description_zh: '消费级四足机器人，适合教育和入门研究。',
    thumbnail: '/library/urdf/unitree/go1_description/thumbnail.png',
    category: 'Quadruped',
    stars: 980,
    downloads: 2100,
    tags: ['Education', 'Quadruped', 'Beginner'],
    tags_zh: ['教育', '四足', '入门'],
    lastUpdated: '2026-01-15',
    urdfPath: '/library/urdf/unitree/go1_description'
  },
  {
    id: '16716bc0-f0da-419c-8038-e182d721e767',
    name: 'Unitree G1',
    name_zh: 'Unitree G1 人形机器人',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'General-purpose humanoid robot for education and research.',
    description_zh: '通用人形机器人，适用于教育和科研。',
    thumbnail: '/library/urdf/unitree/g1_description/thumbnail.png',
    category: 'Humanoid',
    stars: 2100,
    downloads: 4500,
    tags: ['Humanoid', 'Bipedal', 'Research'],
    tags_zh: ['人形', '双足', '科研'],
    lastUpdated: '2026-01-17',
    urdfPath: '/library/urdf/unitree/g1_description',
    urdfFile: 'g1_29dof_with_hand.urdf'
  },
  {
    id: '4ccc81d6-c82d-41d6-b594-038fea7c6610',
    name: 'Unitree H1',
    name_zh: 'Unitree H1 人形机器人',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'High-performance humanoid robot for advanced research.',
    description_zh: '高性能人形机器人，适用于高级研究。',
    thumbnail: '/library/urdf/unitree/h1_description/thumbnail.png',
    category: 'Humanoid',
    stars: 1800,
    downloads: 3800,
    tags: ['Humanoid', 'High-Performance', 'Research'],
    tags_zh: ['人形', '高性能', '科研'],
    lastUpdated: '2026-01-16',
    urdfPath: '/library/urdf/unitree/h1_description'
  },
  {
    id: 'c563d890-6ad0-4f18-bb99-4d182811956f',
    name: 'Unitree H1 2.0',
    name_zh: 'Unitree H1 2.0 人形机器人',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'Second generation high-performance humanoid robot.',
    description_zh: '第二代高性能人形机器人。',
    thumbnail: '/library/urdf/unitree/h1_2_description/thumbnail.png',
    category: 'Humanoid',
    stars: 1500,
    downloads: 2800,
    tags: ['Humanoid', 'Bipedal', 'Next-Gen'],
    tags_zh: ['人形', '双足', '新一代'],
    lastUpdated: '2026-01-18',
    urdfPath: '/library/urdf/unitree/h1_2_description'
  },
  {
    id: 'eae25595-1015-469c-a6d2-feb9bf1daf1f',
    name: 'Unitree H2',
    name_zh: 'Unitree H2 人形机器人',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'Next-generation full-size high-performance humanoid robot for advanced embodied AI research.',
    description_zh: '新一代全尺寸高性能人形机器人。',
    thumbnail: '/library/urdf/unitree/h2_description/thumbnail.png',
    category: 'Humanoid',
    stars: 2300,
    downloads: 4900,
    tags: ['Humanoid', 'High-Performance', 'Full-Size', 'Research'],
    tags_zh: ['人形', '高性能', '全尺寸', '科研'],
    lastUpdated: '2026-02-28',
    urdfPath: '/library/urdf/unitree/h2_description'
  },
  {
    id: '8721701e-9ce2-41a9-98d5-9b15c9fc7ecd',
    name: 'Unitree A1',
    name_zh: 'Unitree A1 四足机器人',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'Agile quadruped robot for dynamic motion research.',
    description_zh: '敏捷四足机器人，适合动态运动研究。',
    thumbnail: '/library/urdf/unitree/a1_description/thumbnail.png',
    category: 'Quadruped',
    stars: 1100,
    downloads: 2500,
    tags: ['Research', 'Quadruped', 'Agile'],
    tags_zh: ['科研', '四足', '敏捷'],
    lastUpdated: '2026-01-14',
    urdfPath: '/library/urdf/unitree/a1_description'
  },
  {
    id: 'df5f6f01-9e7b-43b2-b1e3-9bda3f10ecfa',
    name: 'Unitree B1',
    name_zh: 'Unitree B1 四足机器人',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'Industrial-grade quadruped robot for inspection tasks.',
    description_zh: '工业级四足机器人，适用于巡检任务。',
    thumbnail: '/library/urdf/unitree/b1_description/thumbnail.png',
    category: 'Quadruped',
    stars: 750,
    downloads: 1800,
    tags: ['Industrial', 'Quadruped', 'Inspection'],
    tags_zh: ['工业', '四足', '巡检'],
    lastUpdated: '2026-01-12',
    urdfPath: '/library/urdf/unitree/b1_description'
  },
  {
    id: '4601fd2b-2ec4-48a5-b111-e9d4f6969fd3',
    name: 'Unitree B2',
    name_zh: 'Unitree B2 四足机器人',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'Next-generation industrial quadruped robot.',
    description_zh: '新一代工业四足机器人。',
    thumbnail: '/library/urdf/unitree/b2_description/thumbnail.png',
    category: 'Quadruped',
    stars: 890,
    downloads: 2000,
    tags: ['Industrial', 'Quadruped', 'Inspection'],
    tags_zh: ['工业', '四足', '巡检'],
    lastUpdated: '2026-01-13',
    urdfPath: '/library/urdf/unitree/b2_description'
  },
  {
    id: '1e0c9e37-0b0a-488c-8858-52dc87cdb7c2',
    name: 'Unitree Aliengo',
    name_zh: 'Unitree Aliengo 四足机器人',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'Medium-sized quadruped robot for various applications.',
    description_zh: '中型四足机器人，适用于多种场景。',
    thumbnail: '/library/urdf/unitree/aliengo_description/thumbnail.png',
    category: 'Quadruped',
    stars: 650,
    downloads: 1500,
    tags: ['Research', 'Quadruped', 'General'],
    tags_zh: ['科研', '四足', '通用'],
    lastUpdated: '2026-01-10',
    urdfPath: '/library/urdf/unitree/aliengo_description'
  },
  {
    id: '7158f0eb-8ccf-40b9-b328-30e6ca1c1f74',
    name: 'Unitree A2',
    name_zh: 'Unitree A2 四足机器人',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'Next-generation agile quadruped robot for advanced motion control research.',
    description_zh: '新一代敏捷四足机器人，适合高级运动控制研究。',
    thumbnail: '/library/urdf/unitree/a2_description/thumbnail.png',
    category: 'Quadruped',
    stars: 1050,
    downloads: 2300,
    tags: ['Research', 'Quadruped', 'Agile'],
    tags_zh: ['科研', '四足', '敏捷'],
    lastUpdated: '2026-02-01',
    urdfPath: '/library/urdf/unitree/a2_description'
  },
//   {
//     id: 'edfdd62f-7514-4c24-92db-eb3e4b53d9b9',
//     name: 'Unitree Aliengo Z1',
//     name_zh: 'Unitree Aliengo Z1',
//     author: 'Unitree Robotics',
//     author_zh: '宇树科技',
//     description: 'Aliengo quadruped robot equipped with Z1 manipulator for mobile manipulation.',
//     description_zh: '搭载Z1机械臂的Aliengo四足机器人，具备移动操作能力。',
//     thumbnail: '/library/urdf/unitree/aliengoZ1_description/thumbnail.png',
//     category: 'Quadruped', 
//     stars: 800,
//     downloads: 1600,
//     tags: ['Research', 'Quadruped', 'Mobile Manipulation'],
//     tags_zh: ['科研', '四足', '移动操作'],
//     lastUpdated: '2026-01-20',
//     urdfPath: '/library/urdf/unitree/aliengoZ1_description'
//   },
  {
    id: 'fb1e6be5-b81b-4e31-9a79-ef03df20f099',
    name: 'Unitree B2W',
    name_zh: 'Unitree B2W 轮足机器人',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'Wheeled-legged version of the B2 industrial quadruped robot.',
    description_zh: 'B2工业四足机器人的轮足版本，结合轮式与足式优势。',
    thumbnail: '/library/urdf/unitree/b2w_description/thumbnail.png',
    category: 'Quadruped',
    stars: 920,
    downloads: 1900,
    tags: ['Industrial', 'Wheeled-Legged', 'Inspection'],
    tags_zh: ['工业', '轮足', '巡检'],
    lastUpdated: '2026-01-22',
    urdfPath: '/library/urdf/unitree/b2w_description'
  },
  {
    id: '84b67f98-01ef-4a19-8480-02be36e1b751',
    name: 'Unitree Go2W',
    name_zh: 'Unitree Go2W 轮足机器人',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'Wheeled-legged version of the Go2 quadruped robot for faster mobility.',
    description_zh: 'Go2四足机器人的轮足版本，具备更快的移动速度。',
    thumbnail: '/library/urdf/unitree/go2w_description/thumbnail.png',
    category: 'Quadruped',
    stars: 1150,
    downloads: 2800,
    tags: ['Research', 'Wheeled-Legged', 'Mobile'],
    tags_zh: ['科研', '轮足', '移动'],
    lastUpdated: '2026-01-25',
    urdfPath: '/library/urdf/unitree/go2w_description'
  },
  {
    id: '0abe2a3c-7cf4-4917-a9cd-24a22cf5aa56',
    name: 'Unitree G1 (BrainCo)',
    name_zh: 'Unitree G1 (BrainCo手)',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'Unitree G1 humanoid robot equipped with BrainCo dexterous hands.',
    description_zh: '配备BrainCo灵巧手的G1人形机器人，提升操作灵活性。',
    thumbnail: '/library/urdf/unitree/g1_with_brainco_hand/thumbnail.png',
    category: 'Humanoid',
    stars: 1950,
    downloads: 4100,
    tags: ['Humanoid', 'Bipedal', 'Dexterous'],
    tags_zh: ['人形', '双足', '灵巧操作'],
    lastUpdated: '2026-02-05',
    urdfPath: '/library/urdf/unitree/g1_with_brainco_hand'
  },
  {
    id: '0e3468d6-9c66-465b-b468-9bb006880487',
    name: 'Unitree Laikago',
    name_zh: 'Unitree Laikago 四足机器人',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'The classic Unitree quadruped robot that started it all.',
    description_zh: 'Unitree早期的经典四足机器人，奠定了后续产品基础。',
    thumbnail: '/library/urdf/unitree/laikago_description/thumbnail.png',
    category: 'Quadruped',
    stars: 500,
    downloads: 1200,
    tags: ['Research', 'Quadruped', 'Classic'],
    tags_zh: ['科研', '四足', '经典'],
    lastUpdated: '2025-12-10',
    urdfPath: '/library/urdf/unitree/laikago_description'
  },
  {
    id: '775c203c-5584-48d5-ade5-3be70fa0d3bb',
    name: 'Unitree Dexterous Hand',
    name_zh: 'Unitree 灵巧手',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'Unitree multi-fingered dexterous hand for manipulation research.',
    description_zh: 'Unitree 多指灵巧手，支持精细抓取与操作。',
    thumbnail: '/library/urdf/unitree/dexterous_hand_description/thumbnail.png',
    category: 'Manipulator',
    stars: 700,
    downloads: 1400,
    tags: ['Research', 'Manipulator', 'Hand'],
    tags_zh: ['机械手', '灵巧操作', '科研'],
    lastUpdated: '2026-01-18',
    urdfPath: '/library/urdf/unitree/dexterous_hand_description',
    urdfFile: 'Dex5-URDF-R.urdf'
  },
  {
    id: 'effdf4ce-2856-4f02-9fca-db6a6fa029f4',
    name: 'Unitree Z1',
    name_zh: 'Unitree Z1 机械臂',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'Lightweight collaborative robotic arm.',
    description_zh: '轻量级协作机械臂。',
    thumbnail: '/library/urdf/unitree/z1_description/thumbnail.png',
    category: 'Manipulator',
    stars: 850,
    downloads: 1700,
    tags: ['Manipulator', 'Collaborative', 'Lightweight'],
    tags_zh: ['机械臂', '协作', '轻量'],
    lastUpdated: '2026-01-09',
    urdfPath: '/library/urdf/unitree/z1_description'
  },
  {
    id: 'a230848a-34f7-45b3-b5b2-8caf41e9b1db',
    name: 'Unitree R1',
    name_zh: 'Unitree R1 机器人',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'Unitree R1 intelligent humanoid robot.',
    description_zh: 'Unitree R1 智能人形机器人。',
    thumbnail: '/library/urdf/unitree/r1_description/thumbnail.png',
    category: 'Humanoid',
    stars: 600,
    downloads: 1100,
    tags: ['Humanoid', 'Bipedal', 'Smart'],
    tags_zh: ['人形', '双足', '智能'],
    lastUpdated: '2026-02-10',
    urdfPath: '/library/urdf/unitree/r1_description'
  },
  {
    id: '5985fbd3-85f1-4aff-954d-7c9cc3d045f3',
    name: 'Unitree R1 Air',
    name_zh: 'Unitree R1 Air 机器人',
    author: 'Unitree Robotics',
    author_zh: '宇树科技',
    description: 'Lightweight version of the Unitree R1 humanoid robot.',
    description_zh: 'Unitree R1 Air 智能人形机器人。',
    thumbnail: '/library/urdf/unitree/r1_air_description/thumbnail.png',
    category: 'Humanoid',
    stars: 580,
    downloads: 1050,
    tags: ['Humanoid', 'Bipedal', 'Lightweight', 'Smart'],
    tags_zh: ['人形', '双足', '轻量', '智能'],
    lastUpdated: '2026-02-12',
    urdfPath: '/library/urdf/unitree/r1_air_description'
  }
];
